[project]
name = "chatango-lib"
version = "1.10.3"
description = "Chatango bot library using asyncio"
license = "GPL-3.0-or-later"
readme = "README.md"
authors = [
    { name = "BroiestBro", email = "bro@broiest.com" },
    { name = "LmaoLover", email = "hello@lmao.love" },
    { name = "neokuze", email = "imneokuze@gmail.com" },
    { name = "TheClonerx", email = "theclonerx@outlook.com" },
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.14.1"
]

[build-system]
requires = ["uv_build>=0.11.6,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."
module-name = "chatango"

[dependency-groups]
dev = [
    "black>=23.3.0",
    "isort>=8.0.1",
]
